### ISSUE TITLE
Can not use ECDSA Private Key from keystore file

### ISSUE THREAD

**Issue by whyrulike** [Lagrange-Labs/client-cli#23]
When using cli commands，`./dist/lagrange-cli run -c ./config_holesky.toml`, unable to complete registration。 

INFO[2024-04-18T06:43:57.940Z] Loaded configuration with CommitteeSCAddr 0x57BAf26C77BBBa3D3A8Bd620c8d74B44Bfda8818
Enter the operation to perform (`r`un, re`g`ister, `s`ubscribe, `u`nsubscribe, `c`onfig, `e`xit): g
Do you want to add a new BLS Key Pair? (y/n): y
Do you want to generate a new Key Pair (y/bls_private_key): y
Do you want to add a new BLS Key Pair? (y/n): n
Do you want to generate a new signer private key? (y/n): n
Enter the Signer ECDSA Private Key, if you want to use the stored key, just press `n`: n
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.registerOperator(0xc0001fa8c0)
	/opt/rockx/Lagrange-Labs/client-cli/cmd/main.go:239 +0xcb8
main.run(0xc000200580?)
	/opt/rockx/Lagrange-Labs/client-cli/cmd/main.go:122 +0x2d6
github.com/urfave/cli/v2.(*Command).Run(0xc000200580, 0xc000025ac0, {0xc0001fd980, 0x3, 0x3})
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x9dd
github.com/urfave/cli/v2.(*Command).Run(0xc000200840, 0xc000025a00, {0xc000024080, 0x4, 0x4})
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272 +0xc2e
github.com/urfave/cli/v2.(*App).RunContext(0xc000026600, {0xb218e8?, 0xeee480}, {0xc000024080, 0x4, 0x4})
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x5db
github.com/urfave/cli/v2.(*App).Run(...)
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main()
	/opt/rockx/Lagrange-Labs/client-cli/cmd/main.go:100 +0x1fa`

**Comment by kashishshah** [comment]
In the existing version, you have to create one ECDSA signer key which is specific to State Committees AVS which will be used to verify the identity and signatures of the operator's attestation node. It is not used in governance and/or asset flow.

> This is not you EigenLayer operator's ECDSA key. 

We also have an open issue to support encrypted keystore: https://github.com/Lagrange-Labs/client-cli/issues/19

**Comment by mastereng12** [comment]
will close this in favor of feature changes!
