### ISSUE TITLE
Full support for CLI tool within docker container

### ISSUE THREAD

**Issue by austonst** [Lagrange-Labs/client-cli#59]
Operators may want to run this CLI tool within docker. This provides a few advantages including sandboxing, ability to mount files/directories from custom locations (i.e. outside of ~/.lagrange), and connectivity to RPC endpoints through docker networks.

The provided Dockerfile works well to build the binary, and with proper volume mounting most commands work seamlessly. The main limitation is the `deploy` command, which expects to be run at the OS level, or at least expects access to docker via `exec.Command()`. If the CLI is already running *inside* a docker container, it will not be able to access docker commands and `deploy` fails.

Ideally, the CLI should be able to output a docker-compose file *without* making any calls to docker itself. Operators could then choose to use the workflow of using the containerized CLI for all config and setup, outputting a final docker-compose file, then manually calling `docker compose -f <file> up -d` to start the node without ever running a Lagrange binary at the OS level. Anything to help ease this workflow would be greatly appreciated.

----

Example wrapper script for containerized CLI on all commands except `deploy`:
```
#!/bin/bash
IMAGE="lagrangelabs/lagrange-cli:v0.2.1"
docker run -it --rm --network ethereum -v ./config.toml:/app/config.toml -v ./lagrange:/root/.lagrange $IMAGE /app/lagrange-cli $@
```

**Comment by mastereng12** [comment]
merged!
